'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { cn } from '@/lib/utils'
import { categories, Exam } from '@/lib/mock-data'

interface ExamModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSave: (exam: Partial<Exam>) => void
}

const hoursOptions = [
  { value: '0.5', label: '0.5h' },
  { value: '1', label: '1h' },
  { value: '1.5', label: '1.5h' },
  { value: '2', label: '2h' },
  { value: '3', label: '3h' },
]

export function ExamModal({ open, onOpenChange, onSave }: ExamModalProps) {
  const [title, setTitle] = useState('')
  const [examDate, setExamDate] = useState('')
  const [hoursPerDay, setHoursPerDay] = useState('1')
  const [categoryId, setCategoryId] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)

  useEffect(() => {
    if (!open) {
      setTitle('')
      setExamDate('')
      setHoursPerDay('1')
      setCategoryId('')
    }
  }, [open])

  const handleSubmit = async () => {
    if (!title.trim() || !examDate) return

    setIsGenerating(true)
    // Simulate API call for generating study plan
    await new Promise(resolve => setTimeout(resolve, 1000))

    onSave({
      title: title.trim(),
      examDate: new Date(examDate),
      hoursPerDay: parseFloat(hoursPerDay),
      categoryId: categoryId || 'nauka',
      sessions: [], // Would be generated by API
    })

    setIsGenerating(false)
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[450px]">
        <DialogHeader>
          <DialogTitle>Dodaj egzamin</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Title */}
          <div className="space-y-2">
            <Label htmlFor="exam-title">Tytuł egzaminu *</Label>
            <Input
              id="exam-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="np. Egzamin z Matematyki"
            />
          </div>

          {/* Exam Date */}
          <div className="space-y-2">
            <Label htmlFor="exam-date">Data egzaminu *</Label>
            <Input
              id="exam-date"
              type="date"
              value={examDate}
              onChange={(e) => setExamDate(e.target.value)}
            />
          </div>

          {/* Hours per Day */}
          <div className="space-y-2">
            <Label>Ile godzin dziennie możesz się uczyć?</Label>
            <div className="flex gap-2 flex-wrap">
              {hoursOptions.map((option) => (
                <Button
                  key={option.value}
                  type="button"
                  variant={hoursPerDay === option.value ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setHoursPerDay(option.value)}
                  className={cn(
                    'px-4',
                    hoursPerDay === option.value && 'bg-primary text-primary-foreground'
                  )}
                >
                  {option.label}
                </Button>
              ))}
            </div>
          </div>

          {/* Category */}
          <div className="space-y-2">
            <Label>Kategoria</Label>
            <Select value={categoryId} onValueChange={setCategoryId}>
              <SelectTrigger>
                <SelectValue placeholder="Wybierz kategorię" />
              </SelectTrigger>
              <SelectContent>
                {categories.map((category) => (
                  <SelectItem key={category.id} value={category.id}>
                    <div className="flex items-center gap-2">
                      <div 
                        className="w-3 h-3 rounded-full" 
                        style={{ backgroundColor: category.color }}
                      />
                      {category.name}
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <DialogFooter className="gap-2 sm:gap-0">
          <Button 
            variant="ghost" 
            onClick={() => onOpenChange(false)}
          >
            Anuluj
          </Button>
          <Button 
            onClick={handleSubmit}
            disabled={!title.trim() || !examDate || isGenerating}
            className="bg-primary text-primary-foreground"
          >
            {isGenerating ? 'Generowanie planu...' : 'Generuj plan nauki'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
